export const SPACING = {
  NONE: 0,
  TIGHT: 0.5,
  NORMAL: 1,
  COMFORTABLE: 2,
} as const;

export const LAYOUT = {
  PANEL_MARGIN: SPACING.COMFORTABLE,
  PANEL_PADDING: SPACING.NORMAL,
  HEADER_MARGIN_BOTTOM: SPACING.NORMAL,
  HEADER_MARGIN_LEFT: SPACING.NORMAL,
  CONTENT_MAX_WIDTH: 70,
  FOOTER_HEIGHT: 2,
} as const;
